

name = "upstash-redis"
main = "index.js"
compatibility_date = "2022-05-27"


# Set variables here or on cloudflare
# [vars]
# UPSTASH_REDIS_REST_URL = "REPLACE_THIS"
# UPSTASH_REDIS_REST_TOKEN = "REPLACE_THIS"
