name = "workers-with-redis"
type = "webpack"

account_id = "REPLACE_THIS"
workers_dev = true
route = ""
zone_id = ""

[vars]
UPSTASH_REDIS_REST_URL = "REPLACE_THIS"
UPSTASH_REDIS_REST_TOKEN = "REPLACE_THIS"