name = "cloudflare-service-worker2"
type = "javascript"
zone_id = ""
account_id = ""
route = ""
workers_dev = true
compatibility_date = "2022-04-27"

[build]
command = "npm install && npm run build"
[build.upload]
format = "service-worker"
